### ISSUE TITLE
Proving the postcondition of Fast_Mod

### ISSUE THREAD

**Issue by yannickmoy** [ceberly/sparkmemory#1]
Hi,

I was surprised that the postcondition ``Fast_Mod'Result = A mod B`` could not be proved, but this is because B might not be a power of 2. If you make B of type ``Align_Type`` that you define with a static predicate, then the postcondition is proved.

```ada
   subtype Align_Type is Offset_Type range 1 .. 2**10 with
     Static_Predicate => Align_Type in 2**0 | 2**1 | 2**2 | 2**3 | 2**4 | 2**5
                                     | 2**6 | 2**7 | 2**8 | 2**9 | 2**10;
```

I also changed your parameter mode ``in out`` to ``out`` in ``Arena_Init`` and that worked fine with your example. I wonder what bad behavior you had?

**Comment by yannickmoy** [comment]
by the way, using ``--level=2`` instead of ``--level=0`` is fine for any non-trivial proof, as it just means using 3 provers instead of 1, and using 5 seconds of timeout instead of 1 second.

**Comment by ceberly** [comment]
@yannickmoy I'm so sorry for not seeing this earlier! I made your suggested changes and now the fmod proof works even at level=0. Can't thank you enough, sorry again!
